name: exciting
channels:
  - conda-forge
dependencies:
  - python
  - altair
  - matplotlib
  - numpy
  - pandas
  - plotly
  - requests
  - seaborn
  - vega_datasets
  - pip:
    - dx
    - ipython
    - pandas
    - traitlets>=4.3.1
    - vdom
